wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1678836553.382389
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 19
      - 23
      4: 3.10.9
      5: 0.13.11
      8:
      - 5
update:
  desc: null
  value:
    yaml: <_io.TextIOWrapper name='output/alexnet/config.yaml' mode='r' encoding='UTF-8'>
