wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1678845803.100794
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 19
      - 23
      4: 3.10.9
      5: 0.13.11
      8:
      - 5
batch size:
  desc: null
  value: 512
learning rate:
  desc: null
  value: 0.0003
