BASE: ['resnet18_base.yaml']
DATA:
  BATCH_SIZE: 32
  DATASET: "medium_imagenet"
  IMG_SIZE: 32
  NUM_WORKERS: 32
  PIN_MEMORY: True
MODEL:
  NUM_CLASSES: 200
TRAIN:
  EPOCHS: 20
  WARMUP_EPOCHS: 2
  LR: 3e-4
OUTPUT: "output/resnet18_bs32_autoaug"
SAVE_FREQ: 1
PRINT_FREQ: 500